services:

  stk:
    image: ansys/stk:dev-windowsservercore-ltsc2019
    container_name: stk
    build: 
      context: ./stk-engine
      args:
        baseImage: mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
    environment:
      - ANSYSLMD_LICENSE_FILE=$ANSYSLMD_LICENSE_FILE

  stk-pybase:
    image: ansys/stk:dev-windowsservercore-ltsc2019-pybase
    depends_on:
      - stk
    container_name: stk-pybase
    build: 
      context: ./stk-engine-pybase
      args:
        baseImage: ansys/stk:dev-windowsservercore-ltsc2019
    environment:
      - ANSYSLMD_LICENSE_FILE=$ANSYSLMD_LICENSE_FILE

  stk-python3.11:
    image: ansys/stk:dev-windowsservercore-ltsc2019-python3.11
    depends_on: 
      - stk-pybase 
    container_name: stk-python3.11
    build: 
      context: ./stk-engine-py311
      args:
        baseImage: ansys/stk:dev-windowsservercore-ltsc2019
        basePythonImage: ansys/stk:dev-windowsservercore-ltsc2019-pybase
    environment:
      - ANSYSLMD_LICENSE_FILE=$ANSYSLMD_LICENSE_FILE

  stk-python3.12:
    image: ansys/stk:dev-windowsservercore-ltsc2019-python3.12
    depends_on:
      - stk-pybase 
    container_name: stk-python3.12
    build: 
      context: ./stk-engine-py12
      args:
        baseImage: ansys/stk:dev-windowsservercore-ltsc2019
        basePythonImage: ansys/stk:dev-windowsservercore-ltsc2019-pybase
    environment:
      - ANSYSLMD_LICENSE_FILE=$ANSYSLMD_LICENSE_FILE

  stk-python3.13:
    image: ansys/stk:dev-windowsservercore-ltsc2019-python3.13
    depends_on: 
      - stk-pybase 
    container_name: stk-python3.13
    build: 
      context: ./stk-engine-py313
      args:
        baseImage: ansys/stk:dev-windowsservercore-ltsc2019
        basePythonImage: ansys/stk:dev-windowsservercore-ltsc2019-pybase
    environment:
      - ANSYSLMD_LICENSE_FILE=$ANSYSLMD_LICENSE_FILE


