version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies:pyproject"
    commit-message:
      prefix: "build"
    groups:
      tests:
        patterns:
          - "pytest*"
          - "pytz"
          - "parametrized"
      doc:
        patterns:
          - "jupyter*"
          - "jupytext"
          - "myst*"
          - "nbsphinx"
          - "numpy*"
          - "nbconvert"
          - "*sphinx*"
          - "Pillow"
          - "simplejpeg"
          - "sidecar"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies:ci"
    commit-message:
      prefix: "bump"
    groups:
      actions:
        patterns:
          - "*"
