version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies:pyproject"
    commit-message:
      prefix: "maint"
    groups:
      tests:
        - "pytest*"
        - "pytz"
        - "parametrized"
      doc:
        - "jupyter*"
        - "jupytext"
        - "myst*"
        - "nbsphinx"
        - "numpy*"
        - "*sphinx*"
        - "Pillow"
        - "simplejpeg"
        - "sidecar"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies:ci"
    commit-message:
      prefix: "maint"
    groups:
      actions:
        patterns:
          - "*"
