version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
    labels:
      - "dependencies:pyproject"
    commit-message:
      prefix: "build"
    groups:
      extensions:
        patterns:
          - "matplotlib"
          - "pandas"
      grpc:
        patterns:
          - "grpcio"
          - "protobuf"
      jupyter:
        patterns:
          - "jupyter-rfb"
          - "numpy"
          - "Pillow"
          - "simplejpeg"
          - "sidecar"
      migration:
        patterns:
          - "libcst"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/actions"
    labels:
      - "dependencies:ci"
    commit-message:
      prefix: "build"
    groups:
      actions:
        patterns:
          - "*"
