# -- Defects and glitches labels----------------------------------------------

- name: 'bug'
  description: Defects or glitches reported by users or developers
  color: d42a34

- name: 'fix'
  description:  Pull requests related to resolving problems or errors
  color: d42a34

# -- Documentation labels ----------------------------------------------------

- name: 'docs'
  description: Issues related to documentation
  color: 0677ba

- name: 'docs:api'
  description: Related to API docuemntation
  color: 0677ba

- name: 'docs:examples'
  description: Related to documentation examples
  color: 0677ba

# -- Maintenance labels ------------------------------------------------------

- name: 'maintenance'
  description: Generic maintenance related
  color: f78c37

- name: 'maintenance:ci'
  description: Pipelines maintenance related
  color: f78c37

- name: 'maintenance:docker'
  description: Docker maintenance related
  color: f78c37

# -- Dependencies labels -----------------------------------------------------

- name: 'dependencies'
  description: Related with project dependencies
  color: ffc0cb

- name: 'dependencies:pyproject'
  description: Related with project file dependencies
  color: ffc0cb

- name: 'dependencies:ci'
  description: Related with pipelines dependencies
  color: ffc0cb

# -- Other labels ------------------------------------------------------------

- name: 'release'
  description: Anything related to an incoming release
  color: ffffff

- name: 'good first issue'
  description: Issues suitable for newcomers or those with less experience
  color: 62ca50

- name: 'enhancement'
  description: General improvements to existing features
  color: ffd827

- name: 'code-style'
  description: Improvements related to code style
  color: c2c2c2


