# This file is required by the the action 'https://github.com/actions/labeler'
# and used in the '.github/workflows/ci_cd_pr.yml' workflow

# -- Documentation labels ----------------------------------------------------

'docs':
- any: ['doc/source/**/*.rst']
  all: ['!doc/source/examples.rst', '!doc/source/api/**/*.rst', '!doc/styles/**', '!doc/.vale.ini']

'docs:api':
- any: ['doc/source/api/**/*.rst']

'docs:examples':
- any: ['examples/**/*.py', 'doc/source/examples.rst']

# -- Other labels ------------------------------------------------------------

'code-style':
- any: ['.pre-commit-config.yaml', 'doc/.vale.ini', '.flake8']

'docker':
- any: ['docker/**']

'ci':
- any: ['.github/workflows/**']

'tests':
- any: ['tests/**']
