repos:

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.288
  hooks:
    - id: ruff
      args: [--fix]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
