repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.2
  hooks:
    - id: ruff
      args: [--fix]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
