repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.6
  hooks:
    - id: ruff
      args: [--fix]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    #args: ["--ignore-words='doc/styles/Vocab/ANSYS/accept.txt'",  "--skip='./tests,./doc/_build,./doc/styles'"]
    additional_dependencies:
      - tomli
