[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ansys-stk-core"
dynamic = ["version"]
description = "A Python API for STK"
readme = "README.rst"
requires-python = ">=3.6"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.support@ansys.com"},
]
maintainers = [
    {name = "PyAnsys developers", email = "pyansys.maintainers@ansys.com"},
]

classifiers = [
    # TODO: remove all 'Private' classifiers prior to the public release
    "Private :: Do Not Upload",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
]

[project.optional-dependencies]
tests = [
    "pytest==7.4.2",
    "pytest-cov==4.1.0",
    "pytz==2023.3.post1",
    "parameterized==0.9.0",
]
doc = [
    "ansys-sphinx-theme==0.12.3",
    "enum-tools[sphinx]==0.11.0",
    "numpydoc==1.5.0",
    "sphinx==7.2.6",
    "sphinx-design==0.5.0",
    "sphinx-jinja==2.0.2",
    "sphinx-copybutton==0.5.2",
]

[tool.flit.module]
name = "ansys.stk.core"

[project.urls]
Homepage = "https://www.ansys.com/products/missions/ansys-stk"
Documentation = "https://stk.docs.pyansys.com/"
Source = "https://github.com/pyansys/pystk"
Tracker = "https://github.com/pyansys/pystk/issues"

[tool.black]
line-length = 120
extend-exclude = ["tests"]

[tool.ruff]
line-length = 120
select = [
    "E",    # pycodestyle, see https://beta.ruff.rs/docs/rules/#pycodestyle-e-w
    "D",    # pydocstyle, see https://beta.ruff.rs/docs/rules/#pydocstyle-d
    "F",    # pyflakes, see https://beta.ruff.rs/docs/rules/#pyflakes-f
    "I",    # isort, see https://beta.ruff.rs/docs/rules/#isort-i
    "N",    # pep8-naming, see https://beta.ruff.rs/docs/rules/#pep8-naming-n
    "PTH",  # flake8-use-pathlib, https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth
]
ignore = [
    "E501",  # Line too long. Ignoring this so "black" manages line length.
    "D203",  # One blank line required before class docstring.
    "D204"  # One blank line required after class docstring.
]
extend-exclude = [
    "src/ansys/stk/core/internal/*.py",
    "tests/**/*.py",
]

[tool.ruff.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["ansys"]

[tool.codespell]
ignore-words = "doc/styles/Vocab/ANSYS/accept.txt"

[tool.ruff.mccabe]
max-complexity = 10

[tool.coverage.run]
relative_files = true

[tool.coverage.paths]
source = [
    "src",
    "ansys/stk",
]

[tool.coverage.report]
show_missing = true
