[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ansys-stk-core"
dynamic = ["version"]
description = "A Python API for STK"
readme = "README.rst"
requires-python = ">=3.6"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.support@ansys.com"},
]
maintainers = [
    {name = "PyAnsys developers", email = "pyansys.maintainers@ansys.com"},
]

classifiers = [
    # TODO: remove all 'Private' classifiers prior to the public release
    "Private :: Do Not Upload",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
]

[project.optional-dependencies]
tests = [
    "pytest==7.4.4",
    "pytest-cov==4.1.0",
    "pytz==2023.3.post1",
    "parameterized==0.9.0",
]
doc = [
    "ansys-sphinx-theme==0.13.1",
    "enum-tools[sphinx]==0.11.0",
    "numpydoc==1.5.0",
    "sphinx==7.2.6",
    "sphinx-design==0.5.0",
    "sphinx-jinja==2.0.2",
    "sphinx-copybutton==0.5.2",
    "jupyterlab==4.0.10",
]

[tool.flit.module]
name = "ansys.stk.core"

[project.urls]
Homepage = "https://www.ansys.com/products/missions/ansys-stk"
Documentation = "https://stk.docs.pyansys.com/"
Source = "https://github.com/pyansys/pystk"
Tracker = "https://github.com/pyansys/pystk/issues"

[tool.ruff]
fix = false

[tool.ruff]
line-length = 120
select = [
#    "E",    # pycodestyle, see https://beta.ruff.rs/docs/rules/#pycodestyle-e-w
    "D",    # pydocstyle, see https://beta.ruff.rs/docs/rules/#pydocstyle-d
#    "F",    # pyflakes, see https://beta.ruff.rs/docs/rules/#pyflakes-f
#    "I",    # isort, see https://beta.ruff.rs/docs/rules/#isort-i
#    "N",    # pep8-naming, see https://beta.ruff.rs/docs/rules/#pep8-naming-n
#    "PTH",  # flake8-use-pathlib, https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth
]
ignore = [
#    "E501",  # Line too long. Ignoring this so "ruff.formatter" manages line length.
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in `__init__`
    "D200", # One-line docstring should fit on one line
    "D300", # Use triple double quotes `"""`
    "D400", # First line should end with a period
    "D401", # First line of docstring should be in imperative mood: "Checks equality of the underlying STK references."
    "D404", # First word of the docstring should not be "This"
    "D415", # First line should end with a period, question mark, or exclamation point
    "D417", # Missing argument description in the docstring for `ToPandasDataFrame`: `indexElementName`
]
extend-exclude = [
    "src/ansys/stk/core/internal/*.py",
    "tests/**/*.py",
]

# [tool.ruff.format]
# quote-style = "single"
# indent-style = "tab"

# [tool.ruff.isort]
# combine-as-imports = true
# force-sort-within-sections = true
# known-first-party = ["ansys"]

# TODO: the following configuration has no effect, see issue
# https://github.com/codespell-project/codespell/issues/2375
# At the moment, all codespell configuration is done in the pre-commit file.
# Run: `pre-commit run codespell --all-files --show-diff-on-failure` to recreate
# the conditions under which codespell runs during CI/CD.
# [tool.codespell]
# skip = './src/ansys/stk/core/internal,./tests,./doc/_build,./doc/styles'
# ignore-words = "./doc/styles/Vocab/ANSYS/accept.txt"

[tool.coverage.run]
relative_files = true

[tool.coverage.paths]
source = [
    "src",
    "ansys/stk",
]

[tool.coverage.report]
show_missing = true
