[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ansys-stk-core"
version = "0.1.dev0"
description = "A Python API for STK"
readme = "README.rst"
requires-python = ">=3.6"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.support@ansys.com"},
]
maintainers = [
    {name = "PyAnsys developers", email = "pyansys.maintainers@ansys.com"},
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "importlib-metadata >=4.0",
]

[project.optional-dependencies]
tests = [
    "pytest==7.0.1",
    "pytest-cov==4.0.0",
]
doc = [
    "ansys-sphinx-theme==0.7.1",
    "enum-tools[sphinx]==0.9.0.post1",
    "numpydoc==1.5.0",
    "sphinx==5.3.0",
    "sphinx-copybutton==0.5.1",
]

[tool.flit.module]
name = "ansys.stk.core"

[project.urls]
Homepage = "https://www.ansys.com/products/missions/ansys-stk"
Documentation = "https://stk.docs.pyansys.com/"
Source = "https://github.com/pyansys/pystk"
Tracker = "https://github.com/pyansys/pystk/issues"

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 80
default_section = "THIRDPARTY"
src_paths = ["doc", "src", "tests"]

[tool.coverage.run]
source = ["ansys.stk"]

[tool.coverage.report]
show_missing = true
