services:
  stk-python3.13:
    image: ansys/stk:dev-windowsservercore-ltsc2019-python3.13
    container_name: stk-python3.13
    build: 
      context: .
      args:
        baseImage: ansys/stk:dev-windowsservercore-ltsc2019
        basePythonImage: ansys/stk:dev-windowsservercore-ltsc2019-pybase
    environment:
      - ANSYSLMD_LICENSE_FILE=$ANSYSLMD_LICENSE_FILE
