version: '3.8'
services:
  stk-python3.10:
    image: ansys/stk:latest-centos7-python3.10
    container_name: stk-python3.10
    build: 
      context: .
      args:
        baseImage: ansys/stk:latest-centos7
        basePythonImage: ansys/stk:latest-centos7-pybase
        withGraphics: true
    environment:
      - ANSYSLMD_LICENSE_FILE=$ANSYSLMD_LICENSE_FILE
