from ansys.stk.data_analysis.graphs.graph_functions import *
from ansys.stk.core.stkobjects import *

def azimuth_elevation_time_xy_graph(stk_obj :Sensor, start_time=None, stop_time=None, step=60):
	"""A plot of the direction of the sensor's boresight over time, expressed as azimuth and elevation in body-fixed axes of the sensor's parent.

	This graph wrapper was generated from AGI\STK12\STKData\Styles\Sensor\Azimuth-Elevation.rsg.
	"""
	root = stk_obj.root
	if start_time is None:
		start_time = root.current_scenario.start_time
	if stop_time is None:
		stop_time = root.current_scenario.stop_time
	df = stk_obj.data_providers.item('Boresight AzEl').exec(start_time, stop_time, step).data_sets.to_pandas_dataframe()
	axes = [{'use_unit' : None, 'unit_squared': None, 'ylog10': False, 'y2log10': False, 'label': 'Angle', 'lines': [
			{'y_name':'azimuth', 'label':'Azimuth', 'use_unit':None, 'unit_squared': None, 'unit_pref': 'Angle'},
			{'y_name':'elevation', 'label':'Elevation', 'use_unit':None, 'unit_squared': None, 'unit_pref': 'Angle'}]}]
	return line_chart_time_x(df, root, ['azimuth','elevation'], ['time'], axes, 'Azimuth-Elevation')

def footprint_area_time_xy_graph(stk_obj :Sensor, start_time=None, stop_time=None, step=60):
	"""A plot of the area on the ground inside the sensor footprint over time.

	This graph wrapper was generated from AGI\STK12\STKData\Styles\Sensor\Footprint Area.rsg.
	"""
	root = stk_obj.root
	if start_time is None:
		start_time = root.current_scenario.start_time
	if stop_time is None:
		stop_time = root.current_scenario.stop_time
	df = stk_obj.data_providers.item('Footprint Area').exec(start_time, stop_time, step).data_sets.to_pandas_dataframe()
	axes = [{'use_unit' : None, 'unit_squared': None, 'ylog10': False, 'y2log10': False, 'label': 'Area', 'lines': [
			{'y_name':'area', 'label':'Area', 'use_unit':None, 'unit_squared': None, 'unit_pref': 'Area'}]}]
	return line_chart_time_x(df, root, ['area'], ['time'], axes, 'Footprint Area')

def percent_obscured_time_xy_graph(stk_obj :Sensor, start_time=None, stop_time=None, step=60):
	"""A plot of the percentage that the sensor's field of view is obstructed over time, as generated by Sensor Obscuration tool.

	This graph wrapper was generated from AGI\STK12\STKData\Styles\Sensor\Obscuration.rsg.
	"""
	root = stk_obj.root
	if start_time is None:
		start_time = root.current_scenario.start_time
	if stop_time is None:
		stop_time = root.current_scenario.stop_time
	df = stk_obj.data_providers.item('Obscuration').exec(start_time, stop_time, step).data_sets.to_pandas_dataframe()
	axes = [{'use_unit' : False, 'unit_squared': None, 'ylog10': False, 'y2log10': False, 'label': 'Percent', 'lines': [
			{'y_name':'percent obscured', 'label':'Percent Obscured', 'use_unit':False, 'unit_squared': None, 'unit_pref': 'Percent'}]}]
	return line_chart_time_x(df, root, ['percent obscured'], ['time'], axes, 'Percent Obscured')

