services:
  stk:
    image: ansys/stk:dev-windowsservercore-ltsc2019
    container_name: stk
    build: 
      context: .
      args:
        baseImage: mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
    environment:
      - ANSYSLMD_LICENSE_FILE=$ANSYSLMD_LICENSE_FILE
