name: main
on:
  push:
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.11'
  DOCUMENTATION_CNAME: 'stk.docs.pyansys.com'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  doc-build:
    name: "Doc build excluding 'API' and 'Examples' sections"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

      - name: "Build project documentation excluding 'API' and 'Example' sections"
        uses: ansys/actions/doc-build@v6
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
        env:
          BUILD_API: false
          BUILD_EXAMPLES: false

      - name: "Download the nightly documentation"
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: "Include 'API' and 'Examples' sections from nightly build docs"
        run: |
          # Copy landing pages for 'API' and 'Examples' sections
          cp gh-pages/version/dev/api.html doc/_build/html/api.html
          cp gh-pages/version/dev/examples.html doc/_build/html/examples.html
          # Copy content pages for 'API' and 'Examples' sections
          cp -r gh-pages/version/dev/api doc/_build/html/api
          cp -r gh-pages/version/dev/examples doc/_build/html/examples
          # Copy landing page to include links to previous sections
          cp gh-pages/version/dev/index.html doc/_build/html/index.html

      - name: "Upload combined artifacts"
        uses: actions/upload-artifact@v4
        with:
          path: doc/_build/html
          name: complete-documentation-html

  doc-deploy-dev:
    name: "Deploy dev docs"
    runs-on: ubuntu-latest
    needs: doc-build
    steps:
      - uses: ansys/actions/doc-deploy-dev@v6
        with:
          doc-artifact-name: "complete-documentation-html"
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
