name: release
on:
  push:
    tags:
      - "v*.*.*"

env:
  ANSYS_STK: 'ansys-stk'
  DOCUMENTATION_CNAME: 'stk.docs.pyansys.com'
  LICENSE_SERVER_PORT: '1055'
  MAIN_PYTHON_VERSION: '3.13'
  MINIMUM_PYTHON_VERSION: '3.10'
  PYSTK_DIR: '/home/stk/pystk'
  QUARTO_VERSION: '1.5.55'
  STK_DOCKER_IMAGE: 'ansys/stk-13.0:dev-ubuntu22.04'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Apply the principle of least privilege to state at job level the right
# permissions. More information about workflow permissions in the page
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
permissions: {}

jobs:

  update-changelog:
    name: "Update changelog"
    if: contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: ansys/actions/doc-deploy-changelog@c2fa7c93f6883114e0e643599431b33d29f0b13f # v10.1.4
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  code-style:
    name: "Code style checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Run code style checks"
        uses: ansys/actions/code-style@c2fa7c93f6883114e0e643599431b33d29f0b13f # v10.1.4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  doc-style:
    name: "Doc style checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout project"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: "Install jq"
        run: |
          # Used to format Vale input as a JSON-formatted list of files
          sudo apt install -y jq

      - name: "Collect desired files"
        id: vale
        run: |
          # Find all .rst files excluding those in doc/source/api/
          rst_files=$(find doc/source -type f -name "*.rst" ! -path "doc/source/api/*")

          # Find all .py files inside the examples/ directory, excluding those with an underscore
          python_files=$(find examples -type f -name "*.py" ! -name "*_*")

          # TODO: include Python files too. See Vale issue
          # https://github.com/errata-ai/vale/issues/858
          # Combine both file lists and convert them to a JSON array
          # vale_files=$(echo -e "${rst_files}\n${python_files}" | jq -R . | jq -s .)
          vale_files=$(echo -e "${rst_files}" | jq -R . | jq -s .)
          echo "files=$(jq -c <<< "${vale_files}")" >> "${GITHUB_OUTPUT}"

      - uses: ansys/actions/doc-style@c2fa7c93f6883114e0e643599431b33d29f0b13f # v10.1.4
        with:
          checkout: false
          files: '${{ steps.vale.outputs.files }}'
          vale-config: doc/.vale.ini
          token: ${{ secrets.GITHUB_TOKEN }}
          fail-level: "warning"

  build-wheelhouse:
    name: "Wheelhouse ansys-stk[${{ matrix.target }}] / ${{ matrix.os }} / ${{ matrix.python-version
      }}"
    runs-on: ${{ matrix.os }}
    needs: [code-style, doc-style]
    permissions:
      attestations: write
      contents: read
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
        target: ['core', 'extensions', 'grpc', 'jupyter', 'migration', 'all']
    steps:
      - uses: ansys/actions/build-wheelhouse@c2fa7c93f6883114e0e643599431b33d29f0b13f # v10.1.4
        with:
          library-name: ${{ env.ANSYS_STK }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          target: ${{ matrix.target }}
          attest-provenance: true

  doc-build:
    name: "Doc build"
    runs-on: [self-hosted, pystk]
    needs: build-wheelhouse
    timeout-minutes: 360
    permissions:
      contents: read
    steps:

      - name: "Checkout the project"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: "Download wheelhouse into static path"
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: "doc/source/_static/wheelhouse"
          pattern: "*-wheelhouse-*"

      - name: "Display the wheelhouse layout"
        run: |
          tree doc/source/_static/wheelhouse

      - name: "Generate the name of the Docker image and the container"
        id: docker
        env:
          RUNNER: ${{ runner.name }}
        run: |
          image_name="${STK_DOCKER_IMAGE}-python${MAIN_PYTHON_VERSION}"
          container_name="stk-python${MAIN_PYTHON_VERSION}-${RUNNER}"
          echo "image=${image_name}" >> "${GITHUB_OUTPUT}"
          echo "container=${container_name}" >> "${GITHUB_OUTPUT}"

      - name: "Start the container from the desired image"
        env:
          STK_IMAGE: ${{ steps.docker.outputs.image }}
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
        run: |
          docker run \
            --detach -it \
            --network="host" \
            --name="${STK_CONTAINER}" \
            --env ANSYSLMD_LICENSE_FILE="${LICENSE_SERVER_PORT}@${LICENSE_SERVER}" \
            --volume ${PWD}:/home/stk/pystk \
            "${STK_IMAGE}"

      - name: "Install system dependencies required for building examples"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --user root \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "apt update && apt install -y wget pandoc"

          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "wget --no-check-certificate https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"

          docker exec \
            --user root \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "dpkg -i quarto-${QUARTO_VERSION}-linux-amd64.deb"

          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "quarto install tinytex"

      - name: "Install Tox"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "python -m pip install --upgrade pip tox && rm -rf .tox"

      - name: "Build the full documentation"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "export BUILD_API=true BUILD_EXAMPLES=true && tox -e doc-links,doc-html"

      - name: "Upload HTML documentation artifacts"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: doc/_build/html
          name: documentation-html

      - name: "Stop the container"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        if: always()
        run: |
          docker stop "${STK_CONTAINER}"
          docker logs "${STK_CONTAINER}"
          docker rm "${STK_CONTAINER}"

  tests:
    name: "Tests Python ${{ matrix.python }}"
    runs-on: [self-hosted, pystk]
    needs: code-style
    strategy:
      matrix:
        # Can not use ${{ env.MINIMUM_PYTHON_VERSION }} because GitHub actions
        # does not support ENV variable substitution in matrix definition
        python: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false
    permissions:
      contents: read
    steps:

      - name: "Checkout the project"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: "Generate the name of the Docker image and the container"
        id: docker
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          RUNNER: ${{ runner.name }}
        run: |
          image_name="${STK_DOCKER_IMAGE}-python${PYTHON_VERSION}"
          container_name="stk-python${PYTHON_VERSION}-${RUNNER}"
          echo "image=${image_name}" >> "${GITHUB_OUTPUT}"
          echo "container=${container_name}" >> "${GITHUB_OUTPUT}"

      - name: "Start the container from the desired image"
        env:
          STK_IMAGE: ${{ steps.docker.outputs.image }}
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
        run: |
          docker run \
            --detach -it \
            --network="host" \
            --name="${STK_CONTAINER}" \
            --env ANSYSLMD_LICENSE_FILE="${LICENSE_SERVER_PORT}@${LICENSE_SERVER}" \
            --volume ${PWD}:/home/stk/pystk \
            "${STK_IMAGE}"

      - name: "Install the project with the testing dependencies"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "python -m pip install --upgrade pip tox && rm -rf .tox"

      - name: "Install coverage dependencies"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "python -m pip install --group tests ."

      # -- Tests

      - name: "Run the extensions tests"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "export COVERAGE_FILE=.cov/extensions && tox -e tests-extensions-cov"

      - name: "Run the API migration assistant tests"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "export COVERAGE_FILE=.cov/migration && tox -e tests-core-migration-cov"

      - name: "Run the aviator tests"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "export COVERAGE_FILE=.cov/aviator && tox -e tests-core-aviator-graphics-cov-linux"

      - name: "Run the non graphics stk tests"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "export COVERAGE_FILE=.cov/stknogfx && tox -e tests-core-stk-nographics-cov-linux"

      - name: "Run the graphics only stk tests"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "export COVERAGE_FILE=.cov/stkgfx && tox -e tests-core-stk-graphicsonly-cov-linux"

      - name: "Run the vgt tests"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "export COVERAGE_FILE=.cov/vgt && tox -e tests-core-vgt-graphics-cov-linux"

      - name: "Run the doc snippet tests"
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "export COVERAGE_FILE=.cov/snippets && tox -e tests-core-snippets-graphics-cov-linux"

      # -- Coverage

      - name: "Combine all coverage results"
        if: ${{ matrix.python == env.MINIMUM_PYTHON_VERSION }}
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR}/.cov \
            "${STK_CONTAINER}" /bin/bash -c \
            "export COVERAGE_FILE=coverage && coverage combine aviator stknogfx stkgfx vgt snippets migration extensions"

      - name: "Generate coverage report in XML and HTML"
        if: ${{ matrix.python == env.MINIMUM_PYTHON_VERSION }}
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "coverage html --rcfile pyproject.toml --data-file=.cov/coverage --directory=.cov/${ANSYS_STK}-coverage --fail-under=89"
          docker exec \
            --workdir ${PYSTK_DIR} \
            "${STK_CONTAINER}" /bin/bash -c \
            "coverage xml --rcfile pyproject.toml --data-file=.cov/coverage -o .cov/coverage.xml"

      - name: "Upload ${{ env.ANSYS_STK }} coverage results"
        if: ${{ matrix.python == env.MINIMUM_PYTHON_VERSION }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: .cov/${{ env.ANSYS_STK }}-coverage
          name: ${{ env.ANSYS_STK }}-coverage

      - name: "Upload coverage reports to Codecov"
        if: ${{ matrix.python == env.MINIMUM_PYTHON_VERSION }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: .cov/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: "Stop the container"
        if: always()
        env:
          STK_CONTAINER: ${{ steps.docker.outputs.container }}
        run: |
          docker stop "${STK_CONTAINER}"
          docker logs "${STK_CONTAINER}"
          docker rm "${STK_CONTAINER}"

  build-library:
    name: "Build library"
    runs-on: ubuntu-latest
    needs: [doc-build, tests]
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - uses: ansys/actions/build-library@c2fa7c93f6883114e0e643599431b33d29f0b13f # v10.1.4
        with:
          library-name: ${{ env.ANSYS_STK }}
          attest-provenance: true

  release-pypi:
    name: "Release project to the public PyPI"
    needs: build-library
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:

      - name: "Download the library artifacts from build-library step"
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: ${{ env.ANSYS_STK }}-artifacts
          path: ${{ env.ANSYS_STK }}-artifacts

      - name: "Upload artifacts to PyPI using trusted publisher"
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: "https://upload.pypi.org/legacy/"
          print-hash: true
          packages-dir: ${{ env.ANSYS_STK }}-artifacts
          skip-existing: false

  release-github:
    name: "Release to GitHub"
    needs: release-pypi
    runs-on: ubuntu-latest
    environment: release
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
      - uses: ansys/actions/release-github@c2fa7c93f6883114e0e643599431b33d29f0b13f # v10.1.4
        with:
          library-name: ${{ env.ANSYS_STK }}
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog-release-notes: true
          only-code: true
          add-artifact-attestation-notes: true
          generate_release_notes: false

  doc-deploy-stable:
    name: Deploy stable documentation
    runs-on: ubuntu-latest
    needs: release-github
    permissions:
      contents: write
    steps:
      - uses: ansys/actions/doc-deploy-stable@c2fa7c93f6883114e0e643599431b33d29f0b13f # v10.1.4
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
