name: pull-request
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

env:
  ANSYS_STK: 'ansys-stk'
  DOCUMENTATION_CNAME: 'stk.docs.pyansys.com'
  LICENSE_SERVER_PORT: '1055'
  MAIN_PYTHON_VERSION: '3.13'
  MINIMUM_PYTHON_VERSION: '3.10'
  PYSTK_DIR: '/home/stk/pystk'
  QUARTO_VERSION: '1.5.55'
  STK_DOCKER_IMAGE: 'ansys/stk-12.10:dev-ubuntu22.04'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Apply the principle of least privilege to state at job level the right
# permissions. More information about workflow permissions in the page
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
permissions: {}

jobs:

  debug-container:
    name: "Doc build"
    runs-on: [self-hosted, pystk]
    container:
      image: localhost:5000/ansys/stk-13.0:dev-ubuntu22.04-python3.13
      env:
        ANSYSLMD_LICENSE_FILE: '1055@${{ secrets.LICENSE_SERVER }}'
    permissions:
      contents: read
    steps:

      - name: "List directory"
        run: |
          ls -a

      - name: "Check STK version"
        run: |
          bin/connectconsole -i --noGraphics
